apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: agent
  name: agent-service
spec:
  ports:
  - port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app: agent
  type: NodePort
status:
  loadBalancer: {}
