apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: agent
  name: agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: agent
    spec:
      containers:
      - image: sajithsanal/agent-system-docker:1.0
        name: agent-system-docker
        resources: {}
status: {}
