apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customer
  name: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customer
    spec:
      containers:
      - image: sajithsanal/customer-system-docker:1.0
        name: customer-system-docker
        resources: {}
status: {}
