apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: customer
  name: customer
spec:
  ports:
  - name: 8182-8182
    port: 8182
    protocol: TCP
    targetPort: 8182
  selector:
    app: customer
  type: LoadBalancer
status:
  loadBalancer: {}
