apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ticketing
  name: ticketing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticketing
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ticketing
    spec:
      containers:
      - image: sajithsanal/ticketing-service-docker:1.0
        name: ticketing-service-docker
        resources: {}
status: {}
