apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ticketing
  name: ticketing
spec:
  ports:
  - name: 8183-8183
    port: 8183
    protocol: TCP
    targetPort: 8183
  selector:
    app: ticketing
  type: LoadBalancer
status:
  loadBalancer: {}
