apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: product
  name: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product
    spec:
      containers:
      - image: sajithsanal/product-catalog-docker:1.0
        name: product-catalog-docker
        resources: {}
status: {}
